### ISSUE TITLE
This reading feels overly complex

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/javascript-introduction-to-operators#3]
I think the idea of an operator is actually fairly simple when used in context. Things like math operators are valuable...if you are doing math. Introduce them later down the road when you are doing math. The `==` operator is useful when they are doing `if` statements.  The assignment operator is useful when introducing variables. You haven't done that yet as of this reading so it's super abstract right now

**Comment by pletcher** [comment]
Yeah, this is too abstract. It worked really well to move the stuff covered here to other lessons.
